### ISSUE TITLE
Intiface stuck on 'Engine starting...'

### ISSUE THREAD

**Issue by Wickiot** [intiface/intiface-central#111]
I just installed v2.5.1+18 on Android my Galaxy Tab A8 and launched the first time, the startup stalls on "Starting library internal engine with the following argument: Instance of 'EngineOptionsExternal'".
I killed the app, switched to log level 'All', started again, same result and I see no log indicating any error.

**Comment by qdot** [comment]
Yup, looks like android foregrounding broke in v2.5.1. I'm seeing it on my test phones now too, guess I checked a desynced version. I'll see what I can do about getting a fix in today.

**Comment by qdot** [comment]
Ugh, ok. This shouldn't have passed smoke testing.

In order to catch more crashes, I'd moved our native API loading into requiring a function call rather than static initialization on startup. I made sure this function got called on app startup, but I forgot that, since it was no longer heap initializing, it'd also need to be called when we do foregrounded tasks (which run in basically their own process space). So mobile apps that use foregrounding would start their foreground task, then instantly fail when the API tried to come up and was null.

I guess this didn't get caught in smoke testing because I may have had debug config loaded that were doing in-process servers instead of foregrounding, not sure.

**Comment by qdot** [comment]
Fixed. v2.5.2 for android is on the play store now, iOS in app review.

**Comment by Wickiot** [comment]
Glad it wasn't an issue on my device then, thanks for the quick fix!

**Comment by qdot** [comment]
@Wickiot Just curious, has bluetooth been working ok for you? We've been experiencing random issues with bluetooth on samsung devices.

**Comment by Wickiot** [comment]
I haven't had the device for long, bought in august, but I haven't noticed any issues with bluetooth devices.
