### ISSUE TITLE
"Index out of bounds" when >1 connected via Lovense Connect Mobile

### ISSUE THREAD

**Issue by Permanently** [intiface/intiface-central#154]
When some vibrations happen (via [LethalVibrations](https://github.com/bananasov/LethalVibrations)), they seem to continue forever until the engine is stopped. This has only happened when two devices have been connected via Lovense Connect Mobile; when using only one device this has not been an issue.

![intiface_central_9XvhmzmgFF](https://github.com/user-attachments/assets/139bbceb-f724-4445-ae57-2a48cb29018c)
![intiface_central_Ws6E552lNn](https://github.com/user-attachments/assets/b2767913-af7a-4dd6-9e45-2ab374c6eddd)

(my username is not qdot, and that user does not exist on my machine, so not sure why that's there?)

**Comment by Permanently** [comment]
i've also just realised i've basically admitted that i've been double teaming myself whilst playing lethal company

**Comment by qdot** [comment]
That's me, I'm qDot. The builds happen on my local machine so it encodes my paths in there heh.

Thanks for filing this! I've been seeing this bug pop up in our crash reports but wasn't sure where it came from.

While I should probably fix Lovense Connect and it definitely shouldn't panic: Don't use Lovense Connect. Use Intiface Central on your desktop/phone in repeater mode. There's instructions on that here: https://docs.intiface.com/docs/intiface-central/ui/app-modes-repeater-panel. There's a good chance I'll remove Lovense Connect capabilities soon because it's barely supported even by Lovense themselves.

> i've also just realised i've basically admitted that i've been double teaming myself whilst playing lethal company

We thank you for your service. 🫡

**Comment by Permanently** [comment]
Gotcha, just tried repeater mode and it's working all good now. In my opinion I think Repeater mode should be in the dropdown by default. When I'm not tired, I'll edit the docs to fully describe how to enable it - I got a little confused on the way, but figured it out after [finding this post](https://discuss.buttplug.io/t/how-to-change-server-address-in-buttplugknight/313/2) :^)

In the meantime, I'll just close this since it seems Lovense Connect will be deprecated soon anyway.
