### ISSUE TITLE
Sees but can not connect to lovense devices

### ISSUE THREAD

**Issue by Teila** [intiface/intiface-central#76]
Can find lovense devices but after updating to 2.4.0 errors out connecting
![image](https://github.com/intiface/intiface-central/assets/1573897/1f4f4b18-adab-4bae-855a-6e70c463b7cc)

**Comment by qdot** [comment]
This is most likely due to using an Intel based radio, which does not seem to work well with our system. We recommend trying a different bluetooth radio (i.e. buying the one we recommend in our docs: https://docs.intiface.com/docs/intiface-central/hardware/bluetooth), or in the future when it's fully ready, just using the mobile app.
