### ISSUE TITLE
pubspec.lock should be committed to enable reproducible builds.

### ISSUE THREAD

**Issue by ThatBatLuna** [intiface/intiface-central#86]
In order to be able to reproducibly compile intiface-central on our own machines (or e.g create packages for NixOS, or other reproducible systems) [`pubspec.lock` should be committed](https://dart.dev/guides/libraries/private-files#pubspeclock) (as intiface-central is an application package and not a library). This enables us to make sure that the versions of transitive dependencies match the ones that intiface-central was meant to be built with and prevents weird compilation issues in case of version mismatches.

**Comment by qdot** [comment]
Oh huh. I thought I'd committed that but I guess I wasn't paying attention. I'll try to get it in soon.

**Comment by LovingMelody** [comment]
Looks like .gitignore excludes all lock files, likely why it was ignored.

**Comment by nekowinston** [comment]
I had a shot at [packaging this for Nix](https://github.com/nekowinston/intiface-nix/blob/master/pkgs/intiface-central/default.nix), and managed to get it to build, but had to vendor both `pubspec.lock` & `Cargo.lock`.
The `flutter_rust_bridge = ^1.79.0` dependency without a lockfile will get bumped to `1.82.0`, which then breaks the build (both in `flutter build linux` and `cargo build`, since the API apparently changed).

**Comment by qdot** [comment]
Well funny enough I just opened the project again for the first time since my last comment about 30 minutes ago, so I'll get these files in now. :)

Hoping for a new point release this weekend.

**Comment by qdot** [comment]
Done in 2.4.4
